######################## Default configuration ####################
baseURL = "https://haruyama.studio/"
languageCode = "en"
title = "Haruyama"
theme = "hargo"
summaryLength = "20"
paginate = 10
enableEmoji = "true"

[permalinks]
  blog = "/blog/:filename/"

############################## Navigation ###############################
[menu]

  #[[menu.main]]
  #name = "Work"
  #URL = "work"
  #weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  #[[menu.footer]]
  #name = "Work"
  #URL = "work"
  #weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4

#################### Default parameters ################################
[params]
logo = "images/logo.svg"
home = "Home"
strapline = "Small batch pottery handmade in Cardiff UK"

# Meta data
description = "Small batch pottery handmade in Cardiff UK"
author = "Yoshiharu Yamashita"

goatcounter = "haruyamastudio"

# Contact info
# mobile = ""
email = "yoshiharu.yamashita@outlook.com"
location = "Cardiff UK"

# Count of latest posts to display in footer
countLatestPostsInFooter = 5

# Copyright
copyright = "&copy; 2022 Haruyama"

# Snipcart credentials
# snipcartApiKey = ""
# currencySymbol = ""

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # Product rating (works with https://rating-widget.com/)
  [params.rating]
  enable = false
  websiteID = ""
  publicKey = ""

  # Social sites
  [[params.social]]
  name = "Instagram"
  icon = "ti-instagram"
  link = "https://www.instagram.com/haruyama.studio"

  [[params.social]]
  name = "Twitter"
  icon = "ti-twitter-alt"
  link = "https://twitter.com/haruyamastudio"

  [[params.social]]
  name = "GitHub"
  icon = "ti-github"
  link = "https://github.com/yoshiharuyamashita"

  # Contact form
  [params.contact]
  formAction = "/thank-you/"
